
BOOK_DICT = {
    # AT
    '1Mo': '1 Mose',
    '2Mo': '2 Mose',
    '3Mo': '3 Mose',
    '4Mo': '4 Mose',
    '5Mo': '5 Mose',
    'Jos': 'Josua',
    'Ri': 'Richter',
    'Rut': 'Rut',
    '1Sam': '1 Samuel',
    '2Sam': '2 Samuel',
    '1Kön': '1 Könige',
    '2Kön': '2 Könige',
    '1Chr': '1 Chronik',
    '2Chr': '1 Chronik',
    'Esr':  'Esra',
    'Neh': 'Nehemia',
    'Est': 'Esther',
    'Hi': 'Hiob',
    'Ps': 'Psalmen',
    'Spr': 'Sprüche',
    'Pred': 'Prediger',
    'Hl': 'Hoheslied',
    'Jes': 'Jesaja',
    'Jer': 'Jeremia',
    'Kla': 'Klagelieder',
    'Hes': 'Hesekiel',
    'Dan': 'Daniel',
    'Hos': 'Hosea',
    'Joe': 'Joel',
    'Am': 'Amos',
    'Ob': 'Obadja',
    'Jon': 'Jona',
    'Mi': 'Micha',
    'Nah': 'Nahum',
    'Hab': 'Habakuk',
    'Zef': 'Zephanja',
    'Hag': 'Haggai',
    'Sach': 'Sacharja',
    'Mal': 'Maleachi',

    # NT
    'Mt': 'Matthäus',
    'Mk': 'Markus',
    'Lk': 'Lukas',
    'Joh': 'Johannes',
    'Apg': 'Apostelgeschichte',
    'Röm': 'Römer',
    '1Kor': '1 Korinther',
    '2Kor': '2 Korinther',
    'Gal': 'Galater',
    'Eph': 'Epheser',
    'Phil': 'Philipper',
    'Kol': 'Kolosser',
    '1Thess': '1 Thessalonicher',
    '2Thess': '2 Thessalonicher',
    '1Tim': '1 Timotheus',
    '2Tim': '2 Timotheus',
    'Tit': 'Titus',
    'Phlm': 'Philemon',
    'Hebr': 'Hebräer',
    'Jak': 'Jakobus',
    '1Petr': '1 Petrus',
    '2Petr': '2 Petrus',
    '1Joh': '1 Johannes',
    '2Joh': '2 Johannes',
    '3Joh': '3 Johannes',
    'Jud': 'Judas',
    'Offb': 'Offenbarung'
}